server:
  port: 8080
  host: "0.0.0.0"
  shutdown_timeout: "30s"
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"

database:
  type: "sqlite"
  path: "/data/todos.db"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

kafka:
  brokers:
    - "localhost:9092"
  topic: "todo-events"
  group_id: "todo-app"

metrics:
  enabled: true
  path: "/metrics"
  port: 9090

log:
  level: "info"
  format: "json" 